// <auto-generated />
using System;
using DataAccessObject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122160516_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessObject.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DataAccessObject.Models.CueStick", b =>
                {
                    b.Property<Guid>("CueStickID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CueStickImageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerTurn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CueStickID");

                    b.HasIndex("CueStickImageID");

                    b.ToTable("CueSticks");
                });

            modelBuilder.Entity("DataAccessObject.Models.Image", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CueStickID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DataAccessObject.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductImageID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProductImageID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataAccessObject.Models.Table", b =>
                {
                    b.Property<Guid>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableProduct", b =>
                {
                    b.Property<Guid>("TableProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TableSessionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TableProductID");

                    b.HasIndex("ProductID");

                    b.HasIndex("TableSessionID");

                    b.ToTable("TableProducts");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableSession", b =>
                {
                    b.Property<Guid>("TableSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TableID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TotalHours")
                        .HasColumnType("float");

                    b.HasKey("TableSessionID");

                    b.HasIndex("TableID");

                    b.ToTable("TableSessions");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableSessionCue", b =>
                {
                    b.Property<Guid>("TableSessionCueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CueStickID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TableSessionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TableSessionCueID");

                    b.HasIndex("CueStickID");

                    b.HasIndex("TableSessionID");

                    b.ToTable("TableSessionCues");
                });

            modelBuilder.Entity("DataAccessObject.Models.CueStick", b =>
                {
                    b.HasOne("DataAccessObject.Models.Image", "CueStickImage")
                        .WithMany()
                        .HasForeignKey("CueStickImageID");

                    b.Navigation("CueStickImage");
                });

            modelBuilder.Entity("DataAccessObject.Models.Product", b =>
                {
                    b.HasOne("DataAccessObject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessObject.Models.Image", "ProductImage")
                        .WithMany()
                        .HasForeignKey("ProductImageID");

                    b.Navigation("Category");

                    b.Navigation("ProductImage");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableProduct", b =>
                {
                    b.HasOne("DataAccessObject.Models.Product", "Product")
                        .WithMany("TableProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessObject.Models.TableSession", "TableSession")
                        .WithMany("TableProducts")
                        .HasForeignKey("TableSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableSession", b =>
                {
                    b.HasOne("DataAccessObject.Models.Table", "Table")
                        .WithMany("TableSessions")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableSessionCue", b =>
                {
                    b.HasOne("DataAccessObject.Models.CueStick", "CueStick")
                        .WithMany()
                        .HasForeignKey("CueStickID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessObject.Models.TableSession", "TableSession")
                        .WithMany("TableSessionCues")
                        .HasForeignKey("TableSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CueStick");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DataAccessObject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DataAccessObject.Models.Product", b =>
                {
                    b.Navigation("TableProducts");
                });

            modelBuilder.Entity("DataAccessObject.Models.Table", b =>
                {
                    b.Navigation("TableSessions");
                });

            modelBuilder.Entity("DataAccessObject.Models.TableSession", b =>
                {
                    b.Navigation("TableProducts");

                    b.Navigation("TableSessionCues");
                });
#pragma warning restore 612, 618
        }
    }
}
